wifi_users/urls.py
from django.urls import path

from . import views

app_name = 'wifi_users'

urlpatterns = [
    path('vouchers/', 						views.vouchers, 		name='vouchers'),
    path('create_voucher/', 				views.create_voucher, 	name='create-voucher'),
    path('delete_voucher/<int:voucherId>', 	views.delete_voucher, 	name='delete-voucher'),
]

wifi_voucher/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('wifi_users/', include('wifi_users.urls')),
    path('admin/', admin.site.urls),
]

wifi_users/models.py
from django.db import models

# Create your models here.
class Voucher(models.Model):

	code = models.CharField(max_length=50, null=True)
	quantity = models.CharField(max_length=50)
	max_device = models.CharField(max_length=50)
	voucher_format = models.CharField(max_length=50)
	length = models.CharField(max_length=50)
	duration = models.CharField(max_length=50)
	price = models.CharField(max_length=50)
	purge_after = models.CharField(max_length=50)

wifi_users/views.py
# Django
from django.http 		import HttpResponse
from django.shortcuts 	import render
from django.shortcuts 	import redirect

# Wifi Users
from . viewmodels 		import VoucherViewModel


voucher = VoucherViewModel()


def vouchers(request):

    voucher_list = voucher.get_voucher_list()

    return render(request, 'wifi_users/vouchers.html',
                 {'voucher_list' : voucher_list})


def create_voucher(request):

	if request.method == "GET":

		return render(request, 'wifi_users/create_voucher.html')

	else:

		code = request.POST['code']
		quantity = request.POST['quantity']
		max_device = request.POST['max_device']
		voucher_format = request.POST['voucher_format']
		length = request.POST['length']
		duration = request.POST['duration']
		price = request.POST['price']
		purge_after = request.POST['purge_after']

		voucher.create_new_voucher(code, quantity, max_device, voucher_format, length, duration, price, purge_after)

		return redirect('wifi_users:vouchers')


def delete_voucher(request, voucherId):

	voucher.delete_from_voucher(voucherId)

	return redirect('wifi_users:vouchers')

wifi_users/templates/wifi_users/create_voucher.html
<html>
	<head>
		<title>Create Voucher</title>
	</head>
	<body>
		<center>
			<fieldset style="background-color:233d44">
				<h1 style="color:white" style="font-family:dejavu serif" ><center><b>Create Voucher</b></center></h1>
			</fieldset>
			<br><br>
			<form method="post" action="{% url 'wifi_users:create-voucher' %}">
				{% csrf_token %}
				Code: <input placeholder="Code" type="text" name="code"></br><br>
				Quantity: <input placeholder="Quantity" type="text" name="quantity"></br><br>
				Max Device: <input placeholder="Max Device" type="text" name="max_device"></br><br>
				Voucher Format: <input placeholder="Voucher Format" type="text" name="voucher_format"></br><br>
				Length: <input placeholder="Length" type="text" name="length"></br><br>
				Duration: <input placeholder="Duration" type="text" name="duration"></br><br>
				Price: <input placeholder="Price" type="text" name="price"></br><br>
				Purge After: <input placeholder="Purge After" type="text" name="purge_after"></br><br>
				<input type="submit" name="create"></br>
			</form>
		</center>
	</body>
</html>

wifi_users/templates/wifi_users/vouchers.html
<html>
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	</head>
	<div class="container mt-4">
		<div class="row">
			<div class="col-lg-12">
				<ul class="breadcrumb">
					<button class="btn btn-primary" onclick="location.href='{% url 'wifi_users:create-voucher' %}'">
						<i class="ft-plus"></i> Create Voucher
					</button>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						<table class="table">
							<thead class="white bg-light">
								<tr>
									<th>Code</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								{% for voucher in voucher_list %}
								<tr>
									<td>{{voucher.code}}</td>
									<td><a href="{% url 'wifi_users:delete-voucher' voucher.id %}">Delete</a></td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</html>